name: food_subs
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  get: ^4.6.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.0
  dotted_border: ^2.1.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_sticky_header: ^0.6.5
  flutter_snake_navigationbar: ^0.6.1
  cached_network_image: ^3.3.1
  lottie: ^3.1.2
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/json/
